name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Intall dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bunx prisma generate

      - name: Run tests
        run: bun test
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          APP_URL: ${{ secrets.APP_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to railway
        run: railway up --service hono-lab
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
          RAILWAY_PROJECT_ID: ee5266ca-3564-4776-a8b5-0004e07e9893
